dist: bionic
language: python


matrix:
  include:
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=mypy
    - python: 3.8
      env: TOXENV=pylint
    - python: 3.8
      env: TOXENV=black

    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9-dev
      env: TOXENV=py39
    - python: pypy3.6-7.2.0
      env: TOXENV=pypy36


install:
  - pip install tox


script:
  - tox


deploy:
  provider: pypi
  user: henningu
  password:
    secure: Q7ttVWDM3hQGlMnCIH4Ny5b2ZqRCGPAfisfi9VnAOM2+cgR+0T1EbA2SO5OqYKGifNZ5WQ2P0iq+1cVSFfMhRuSxqqaVtp6nsKJv/kvn6dh27oA/K68QjYsrmrtcRGnlUYzx+rCMQbg9/lUAs7yYKEMp3Sp1GlGb8TcKia+inpsc5h8ysiSJPtkTj6Q+VndrUbRy1jQoRD0vcqM09rZpDMaezak8O1scopxn4/xWqM2geE/hye2qD9T7PG6gj1htd5kWiTdi5b0sNlghgx7lacY28aDkn0fF4P+QQrQe9EK1lsGEi+Nx7ug1P/rqWrfTgceRwuAAJHQLTeEgkmoDWCLd/zD0uRBxA1Z4VRsGP6fk/St81QpHRxA3eU/vLM+cDmy7jNhxKM/d/SWOhuZH6SWiOoBzoZUGUwCfopn/iUXumVTPuBZ6E7UTcLOp0PWnijhY9rwDKanZ+Ku0iyr9SDeslZj296/LvMNQ+L/MDtkn16ba/nNTrCHGzpv+XknKFYd7dF264ac6Oj+ncgWJ/wSV9HzDY054oVUYtEuk+N5fcNECAe86O3G2Zn6dajDUZlkQ74sksz4wr/ToICK6vjKaZYJoetpxo/SvqAMaby7dL4svIhS2ImNXbmmqwhYA9C8MY7nSEGYuRI51um9jXYNucOzOGkom2mmVq0YrSjc=
  skip_existing: true
  on:
    branch: master
