name: setuptools

on: [push, pull_request]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
            os: ubuntu-latest
            os: macos-latest
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: python -m pip install --upgrade pip
      - name: setup
        run: python setup.py install