name: tests

on: [push, pull_request]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.8
            toxenv: flake8
            os: ubuntu-latest
          - python: 3.8
            toxenv: mypy
            os: ubuntu-latest
          - python: 3.8
            toxenv: pylint
            os: ubuntu-latest
          - python: 3.8
            toxenv: black
            os: ubuntu-latest

          - python: 3.7
            toxenv: py37
            os: ubuntu-latest
          - python: 3.8
            toxenv: py38
            os: ubuntu-latest
          - python: 3.9
            toxenv: py39
            os: ubuntu-latest
          - python: pypy-3.7
            toxenv: pypy37
            os: ubuntu-latest

          - python: 3.8
            toxenv: py38
            os: macos-latest
          - python: 3.8
            toxenv: py38
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{  matrix.python }}
      - name: replace css dependency (win)
        shell: pwsh
        if: github.ref != 'refs/heads/master' && runner.os == 'Windows' && !(github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master')
        run: (Get-Content setup.py) -replace 'comb-spec-searcher==\d+.\d+.\d+', $('comb-spec-searcher@git+https://github.com/PermutaTriangle/comb_spec_searcher"' + $([environment]::newline) + '        "@develop') | Out-File -encoding UTF8 setup.py
      - name: replace css dependency (unix)
        if: github.ref != 'refs/heads/master' && runner.os != 'Windows' && !(github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master')
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install gnu-sed
            gsed -i -E 's/comb-spec-searcher==[0-9]+.[0-9]+.[0-9]+/comb-spec-searcher@git+https:\/\/github.com\/PermutaTriangle\/comb_spec_searcher"\n        "@develop/g' setup.py
            cat setup.py
          else
            sed -i -E 's/comb-spec-searcher==[0-9]+.[0-9]+.[0-9]+/comb-spec-searcher@git+https:\/\/github.com\/PermutaTriangle\/comb_spec_searcher"\n        "@develop/g' setup.py
          fi
      - name: install dependencies
        run: python -m pip install --upgrade pip tox
      - name: run
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
      - name: setup
        run: python setup.py install
