name: tests

on: [push, pull_request]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.13"
            toxenv: flake8
            os: ubuntu-latest
          - python: "3.13"
            toxenv: mypy
            os: ubuntu-latest
          - python: "3.13"
            toxenv: pylint
            os: ubuntu-latest
          - python: "3.13"
            toxenv: black
            os: ubuntu-latest

          - python: "3.10"
            toxenv: py310
            os: ubuntu-latest
          - python: "3.11"
            toxenv: py311
            os: ubuntu-latest
          - python: "3.12"
            toxenv: py312
            os: ubuntu-latest
          - python: "3.13"
            toxenv: py313
            os: ubuntu-latest

          - python: "pypy-3.10"
            toxenv: pypy310
            os: ubuntu-latest
          - python: "pypy-3.11"
            toxenv: pypy311
            os: ubuntu-latest

          - python: "3.13"
            toxenv: py310
            os: macos-latest
          - python: "3.13"
            toxenv: py310
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{  matrix.python }}
      - name: Install dependencies from develop branch
        if: github.ref != 'refs/heads/master' && !(github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master')
        run: |
          echo "Installing dependencies from develop branches instead of PyPI"
          python -m pip install git+https://github.com/PermutaTriangle/comb_spec_searcher.git@develop
          python -m pip install git+https://github.com/PermutaTriangle/Permuta.git@develop
          
          # Optional: Install the project in development mode to work with the new dependencies
          python -m pip install -e .
          
          # Verify installed versions
          echo "Checking installed comb_spec_searcher version:"
          python -c "import comb_spec_searcher; print(comb_spec_searcher.__version__)"
          echo "Checking installed permuta version:"
          python -c "import permuta; print(permuta.__version__)"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip tox
          pip install setuptools wheel twine
      - name: run
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
      - name: setup
        run: python setup.py install
